### ISSUE TITLE
info.json 解码出错

### ISSUE THREAD

**Issue by Mycluster-1** [Khoray/zhihuishuInteract_khoray#2]
info.json 解码出错
任务开始
Traceback (most recent call last):
  File "C:/Users/504/Desktop/AnsRepeater-master/main.py", line 268, in <module>
    spider = Spider(info)
NameError: name 'info' is not defined

**Comment by Khoray** [comment]
AnsRepeater是隔壁的吧0.0

**Comment by Mycluster-1** [comment]
报错如下 是我的cookie不对吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Khoray"<notifications@github.com&gt;; 
发送时间: 2020年11月11日(星期三) 中午1:10
收件人: "Khoray/zhihuishuInteract_khoray"<zhihuishuInteract_khoray@noreply.github.com&gt;; 
抄送: "林先生"<2283463673@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Khoray/zhihuishuInteract_khoray] info.json 解码出错 (#2)






关闭#2.

—
你收到这个是因为你编写了这个线程。
直接回复此邮件，在GitHub上查看，或取消订阅.
